#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: tap
    kapp.k14s.io/change-rule.serviceaccount-del: "delete before deleting tap-serviceaccount"
    kapp.k14s.io/change-rule.external-dns-del: "delete before deleting external-dns"
    kapp.k14s.io/change-rule.external-dns-upsert: "upsert after upserting external-dns"
  name: tap
  namespace: tap-install
spec:
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.4.0 <1.5.0"
      prereleases: {}
  serviceAccountName: tap-package-install-sa
  values:
  - secretRef:
      name: tap-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tap-install
stringData:
  #@yaml/text-templated-strings
  tap-values.yaml: |
    profile: (@= data.values.tap.profile @)
    ceip_policy_disclosed: true

    shared:
      ingress_domain: (@= data.values.tap.domain @)
      image_registry:
        project_path: (@= data.values.registry.url @)/tap
        username: (@= data.values.registry.username @)
        password: (@= data.values.registry.password @)
    
    supply_chain: basic

    image_policy_webhook:
      allow_unmatched_tags: true

    appliveview_connector:
      backend:
        sslDeactivated: false
        ingressEnabled: true
        host: appliveview.(@= data.values.tap.view_cluster_domain @)

    tap_telemetry:
      installed_for_vmware_internal_use: "true"
    
    namespace_provisioner:
      controller: false
      additional_sources:
      - git:
          url: git@github.com:cdelashmutt-pivotal/test-private.git
          ref: origin/master
          subPath: custom-resources
          secretRef:
            name: git-ssh
        path: _ytt_lib/objects