apiVersion: tf.isaaguilar.com/v1alpha2
kind: Terraform
metadata:
  name: aks-tap
  namespace: aks-tap
spec:
  credentials:
  - secretNameRef:
      name: aks-tap-azure
  keepLatestPodsOnly: true
  terraformVersion: "1.3.7"
  terraformModule:
    source: https://github.com/cdelashmutt-pivotal/terraform-accelerator.git

  backend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "aks-tap"
        in_cluster_config  = true
        namespace = "aks-tap"
      }
    }